[2025-07-06T11:08:36.545+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T11:08:36.554+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_task scheduled__2025-07-04T12:00:00+00:00 [queued]>
[2025-07-06T11:08:36.561+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_task scheduled__2025-07-04T12:00:00+00:00 [queued]>
[2025-07-06T11:08:36.561+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-07-06T11:08:36.575+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): hello_task> on 2025-07-04 12:00:00+00:00
[2025-07-06T11:08:36.582+0000] {standard_task_runner.py:57} INFO - Started process 346 to run task
[2025-07-06T11:08:36.584+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'hello_task', 'scheduled__2025-07-04T12:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpwtndemrd']
[2025-07-06T11:08:36.586+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask hello_task
[2025-07-06T11:08:36.599+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T11:08:36.628+0000] {task_command.py:410} INFO - Running <TaskInstance: hello_world.hello_task scheduled__2025-07-04T12:00:00+00:00 [running]> on host 5ed82222854b
[2025-07-06T11:08:36.638+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T11:08:36.708+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_world' AIRFLOW_CTX_TASK_ID='hello_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-04T12:00:00+00:00'
[2025-07-06T11:08:36.709+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-06T11:08:36.709+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello from Airflow']
[2025-07-06T11:08:36.723+0000] {subprocess.py:86} INFO - Output:
[2025-07-06T11:08:36.725+0000] {subprocess.py:93} INFO - Hello from Airflow
[2025-07-06T11:08:36.725+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-06T11:08:36.752+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_task, execution_date=20250704T120000, start_date=20250706T110836, end_date=20250706T110836
[2025-07-06T11:08:36.796+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-06T11:08:36.819+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
